# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: AGNTCY.shadictl
PackageVersion: 0.1.3
InstallerType: zip
NestedInstallerType: portable
Commands:
- shadictl
ReleaseDate: 2026-07-28
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/agntcy/shadi/releases/download/agntcy-shadi-cli-v0.1.3/shadictl-v0.1.3-x86_64-pc-windows-msvc.zip
  InstallerSha256: 1FE62E470A16DF665146119764C8605FE80221B97676704AEBF42623CA0E7F63
  NestedInstallerFiles:
  - RelativeFilePath: shadictl-v0.1.3-x86_64-pc-windows-msvc\shadictl.exe
    PortableCommandAlias: shadictl
ManifestType: installer
ManifestVersion: 1.12.0
